### ISSUE TITLE
.net 4.0

### ISSUE THREAD

**Issue by ignatandrei** [ignatandrei/Exporter#31]

**Comment by marcelo-fabiano** [comment]
Ok, but now? what to do?

**Comment by ignatandrei** [comment]
I will solve it . And let you know.

**Comment by ignatandrei** [comment]
Make a branch: https://github.com/ignatandrei/Exporter/tree/branchNet4

**Comment by ignatandrei** [comment]
The fact that is .NET 4.0 : Run in powershell

[Reflection.Assembly]::ReflectionOnlyLoadFrom("ExporterConsole.exe").ImageRuntimeVersion

Answer:
v4.0.30319

Please tell me that all is ok to close the issue.
